import { Product, categories, CategorySlug } from './products';

export type { CategorySlug };
export { categories };

export const products: Product[] = [
  {
    id: 'cf-polo-001',
    name: 'Navy Herringbone Knit Polo',
    category: 'polos',
    series: 'Essential Collection',
    images: ['/products/polo-navy.jpg'],
    wholesalePrice: 4.20,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.20 },
      { minQty: 100, maxQty: 249, unitPrice: 3.50 },
      { minQty: 250, maxQty: null, unitPrice: 3.20 },
    ],
    moq: 50,
    leadTime: '15-20 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    sku: 'CF-PO-001',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge knit',
      lining: 'Breathable cotton blend',
      craft: 'Herringbone textured stitch | Ribbed trim',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Classic polo collar with ribbed construction',
      '2-button placket with dark round buttons',
      'Subtle all-over herringbone textured stitch pattern',
      'Ribbed sleeve cuffs and bottom hem',
      'Tailored slim fit for a refined silhouette',
    ],
    description: 'A refined knit polo in deep navy blue with a distinctive herringbone texture. Crafted from premium imported yarn with a fine-gauge knit that balances structure and comfort. The subtle textured pattern elevates this beyond a basic polo, making it versatile for both smart-casual office wear and weekend outings.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Store folded to maintain shape.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 'cf-polo-002',
    name: 'Black Zip-Neck Knit Polo',
    category: 'polos',
    series: 'Essential Collection',
    images: ['/products/polo-zip-black.jpg'],
    wholesalePrice: 4.50,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.50 },
      { minQty: 100, maxQty: 249, unitPrice: 3.80 },
      { minQty: 250, maxQty: null, unitPrice: 3.50 },
    ],
    moq: 50,
    leadTime: '15-20 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    sku: 'CF-PO-002',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge smooth knit',
      lining: 'Breathable cotton blend',
      craft: 'Smooth knit construction | Silver-tone zipper',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Modern half-zip placket with sleek silver-tone zipper',
      'Classic polo collar with clean lines',
      'Smooth fine-gauge knit for a polished look',
      'Ribbed sleeve cuffs and bottom hem',
      'Lightweight and breathable for all-day comfort',
    ],
    description: 'A modern take on the classic polo, featuring a sleek half-zip placket in solid black. The fine-gauge smooth knit creates a refined, elevated look that transitions seamlessly from day to evening. Lightweight and breathable, this piece embodies effortless sophistication.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Store folded to maintain shape.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'cf-polo-003',
    name: 'White Zip-Neck Knit Polo',
    category: 'polos',
    series: 'Essential Collection',
    images: ['/products/polo-zip-white.jpg'],
    wholesalePrice: 4.50,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.50 },
      { minQty: 100, maxQty: 249, unitPrice: 3.80 },
      { minQty: 250, maxQty: null, unitPrice: 3.50 },
    ],
    moq: 50,
    leadTime: '15-20 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'White', hex: '#FFFFFF' },
    ],
    sku: 'CF-PO-003',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge smooth knit',
      lining: 'Breathable cotton blend',
      craft: 'Smooth knit construction | Silver-tone zipper',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Modern half-zip placket with sleek silver-tone zipper',
      'Classic white polo collar with clean lines',
      'Smooth fine-gauge knit in crisp white',
      'Ribbed sleeve cuffs and bottom hem',
      'Versatile pairing with any trouser color',
    ],
    description: 'The white counterpart to our signature zip-neck polo. Crisp and clean, this piece brings a fresh, polished look to any warm-weather wardrobe. The fine-gauge knit drapes beautifully, while the half-zip detail adds a contemporary edge to a timeless silhouette.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Wash separately to prevent color transfer.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: 'cf-polo-004',
    name: 'Black Contrast-Trim Zip Polo',
    category: 'polos',
    series: 'Signature Collection',
    images: ['/products/polo-contrast-black.jpg'],
    wholesalePrice: 4.80,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.80 },
      { minQty: 100, maxQty: 249, unitPrice: 4.20 },
      { minQty: 250, maxQty: null, unitPrice: 3.50 },
    ],
    moq: 50,
    leadTime: '18-22 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'Black/Grey', hex: '#1A1A1A' },
    ],
    sku: 'CF-PO-004',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge knit',
      lining: 'Breathable cotton blend',
      craft: 'Contrast ribbed trim | Silver-tone zipper',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Contrasting dark grey ribbed polo collar',
      'Half-zip placket with sleek silver-tone zipper',
      'Matching contrast grey ribbed sleeve cuffs',
      'Black body with refined two-tone design',
      'Tailored slim fit for modern styling',
    ],
    description: 'A statement polo that plays with contrast. The black body is framed by dark grey ribbed trim at the collar and cuffs, creating a subtle yet distinctive two-tone effect. The half-zip closure adds a sporty-luxe sensibility. A piece that stands out while maintaining understated elegance.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Wash dark colors separately.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'cf-polo-005',
    name: 'Espresso Brown Contrast Collar Polo',
    category: 'polos',
    series: 'Signature Collection',
    images: ['/products/polo-brown-contrast.jpg'],
    wholesalePrice: 4.80,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.80 },
      { minQty: 100, maxQty: 249, unitPrice: 4.20 },
      { minQty: 250, maxQty: null, unitPrice: 3.50 },
    ],
    moq: 50,
    leadTime: '18-22 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'Espresso Brown', hex: '#3E2723' },
    ],
    sku: 'CF-PO-005',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge knit',
      lining: 'Breathable cotton blend',
      craft: 'Contrast ribbed collar and cuffs | Stripe detail',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Contrasting medium grey ribbed polo collar',
      'Thin brown stripe accent along collar edge',
      'Matching grey ribbed cuffs with brown stripe detail',
      'Deep espresso brown body for rich warmth',
      'Half-zip placket with sleek silver-tone zipper',
    ],
    description: 'Rich espresso brown meets cool grey in this sophisticated contrast-collar polo. The grey collar and cuffs feature a thin brown stripe that ties the two tones together seamlessly. A masterclass in refined color coordination that adds depth to any ensemble.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Wash dark colors separately.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 'cf-polo-006',
    name: 'White Sand-Trim Zip Polo',
    category: 'polos',
    series: 'Signature Collection',
    images: ['/products/polo-white-contrast.jpg'],
    wholesalePrice: 4.80,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 4.80 },
      { minQty: 100, maxQty: 249, unitPrice: 4.20 },
      { minQty: 250, maxQty: null, unitPrice: 3.50 },
    ],
    moq: 50,
    leadTime: '18-22 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'White/Sand', hex: '#F5F0EB' },
    ],
    sku: 'CF-PO-006',
    material: {
      fabric: 'Premium high-count imported yarn | Fine-gauge knit',
      lining: 'Breathable cotton blend',
      craft: 'Contrast ribbed collar and cuffs | Stripe detail',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 22 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 23 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 24 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 25 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 74, sleeve: 26 },
    ],
    designDetails: [
      'Warm sand/beige contrasting ribbed polo collar',
      'Two thin white stripe accents along collar edge',
      'Matching sand ribbed cuffs with white stripe detail',
      'Crisp white body with warm neutral trim',
      'Half-zip placket with clean zipper pull',
    ],
    description: 'A fresh interpretation of contrast design. The white body is complemented by a warm sand-colored collar and cuffs, accented with delicate white stripes. This subtle interplay of neutral tones creates an effortlessly elegant look that pairs beautifully with both light and dark trousers.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Wash white colors separately.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 'cf-tee-001',
    name: 'Chocolate Brown Ribbed Knit Tee',
    category: 't-shirts',
    series: 'Essential Collection',
    images: ['/products/tee-brown.jpg'],
    wholesalePrice: 3.20,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.20 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '12-15 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'Chocolate Brown', hex: '#4E342E' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    sku: 'CF-TE-001',
    material: {
      fabric: 'Premium rib-knit yarn | Vertical ribbed texture',
      lining: 'Breathable cotton blend',
      craft: 'All-over vertical rib-knit | Stretch construction',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 88, waist: 78, hip: 88, length: 64, sleeve: 20 },
      { size: 'M', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 21 },
      { size: 'L', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 22 },
      { size: 'XL', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 23 },
      { size: 'XXL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 24 },
    ],
    designDetails: [
      'All-over vertical rib-knit texture',
      'Ribbed crewneck collar',
      'Ribbed sleeve cuffs and bottom hem',
      'Slim body-conscious fit with natural stretch',
      'Clean, minimal design without logos',
    ],
    description: 'An elevated essential in deep chocolate brown. The all-over vertical rib-knit creates a distinctive textured look while providing natural stretch for a comfortable, body-conscious fit. This piece bridges the gap between a casual tee and a polished knit, perfect for smart-casual occasions.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Store folded.',
    certifications: ['OEKO-TEX Standard 100'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 'cf-tee-002',
    name: 'White Ribbed Knit Tee',
    category: 't-shirts',
    series: 'Essential Collection',
    images: ['/products/tee-white.jpg'],
    wholesalePrice: 3.20,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.20 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '12-15 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'White', hex: '#FFFFFF' },
    ],
    sku: 'CF-TE-002',
    material: {
      fabric: 'Premium rib-knit yarn | Vertical ribbed texture',
      lining: 'Breathable cotton blend',
      craft: 'All-over vertical rib-knit | Stretch construction',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 88, waist: 78, hip: 88, length: 64, sleeve: 20 },
      { size: 'M', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 21 },
      { size: 'L', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 22 },
      { size: 'XL', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 23 },
      { size: 'XXL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 24 },
    ],
    designDetails: [
      'All-over vertical rib-knit texture in crisp white',
      'Ribbed crewneck collar',
      'Ribbed sleeve cuffs and bottom hem',
      'Slim body-conscious fit with natural stretch',
      'Clean, minimal design without logos',
    ],
    description: 'The white counterpart to our signature ribbed knit tee. Crisp, clean, and endlessly versatile, this piece works as a standalone in warm weather or layered under blazers and jackets in cooler months. The ribbed texture adds visual interest and a refined hand feel.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Store folded. Wash white colors separately.',
    certifications: ['OEKO-TEX Standard 100'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 'cf-tee-003',
    name: 'Warm Brown Ribbed Knit Tee',
    category: 't-shirts',
    series: 'Essential Collection',
    images: ['/products/tee-warm-brown.jpg'],
    wholesalePrice: 3.20,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.20 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '12-15 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'Warm Brown', hex: '#8D6E63' },
    ],
    sku: 'CF-TE-003',
    material: {
      fabric: 'Premium rib-knit yarn | Fine-gauge ribbed texture',
      lining: 'Breathable cotton blend',
      craft: 'All-over vertical rib-knit | Stretch construction',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 88, waist: 78, hip: 88, length: 64, sleeve: 20 },
      { size: 'M', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 21 },
      { size: 'L', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 22 },
      { size: 'XL', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 23 },
      { size: 'XXL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 24 },
    ],
    designDetails: [
      'Warm medium brown with subtle vertical rib texture',
      'Ribbed crewneck collar',
      'Ribbed banded short sleeves',
      'Modern fitted cut that follows the torso',
      'Plain, unadorned front and back',
    ],
    description: 'A warm, approachable brown in our signature ribbed knit construction. The medium-brown tone is rich without being heavy, making it a versatile piece that pairs naturally with white, black, or earth-toned bottoms. The ribbed texture elevates this beyond a basic tee.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Store folded.',
    certifications: ['OEKO-TEX Standard 100'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 'cf-tee-004',
    name: 'Charcoal Stripe Knit Tee',
    category: 'striped-tees',
    series: 'Stripe Collection',
    images: ['/products/tee-stripe-charcoal.jpg', '/products/tee-stripe-detail.jpg'],
    wholesalePrice: 3.50,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.50 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '15-18 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'Charcoal/White', hex: '#424242' },
    ],
    sku: 'CF-TE-004',
    material: {
      fabric: 'Fine-gauge knit | Soft breathable cotton blend',
      lining: 'Skin-friendly cotton',
      craft: 'Horizontal stripe pattern | Ribbed trim construction',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 90, waist: 80, hip: 90, length: 65, sleeve: 21 },
      { size: 'M', chest: 94, waist: 84, hip: 94, length: 67, sleeve: 22 },
      { size: 'L', chest: 98, waist: 88, hip: 98, length: 69, sleeve: 23 },
      { size: 'XL', chest: 102, waist: 92, hip: 102, length: 71, sleeve: 24 },
      { size: 'XXL', chest: 106, waist: 96, hip: 106, length: 73, sleeve: 25 },
    ],
    designDetails: [
      'Charcoal grey base with wide white stripes and narrow multi-stripe groups',
      'Classic ribbed crewneck collar',
      'Ribbed sleeve cuffs and bottom hem',
      'Balanced horizontal stripe pattern mixing wide and thin lines',
      'Soft, breathable, and sweat-wicking fabric',
    ],
    description: 'A refined take on the striped tee. The charcoal base features a considered pattern of wide white stripes and clusters of thin white lines, creating visual rhythm without overwhelming. The fine-gauge knit is soft, breathable, and suitable for multi-scene versatility.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Wash dark colors separately.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'cf-tee-005',
    name: 'Grey Horizontal Stripe Tee',
    category: 'striped-tees',
    series: 'Stripe Collection',
    images: ['/products/tee-stripe-grey.jpg'],
    wholesalePrice: 3.50,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.50 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '15-18 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'Dark Grey/White', hex: '#616161' },
    ],
    sku: 'CF-TE-005',
    material: {
      fabric: 'Fine-gauge knit | Soft breathable cotton blend',
      lining: 'Skin-friendly cotton',
      craft: 'Horizontal stripe pattern | Ribbed trim construction',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 90, waist: 80, hip: 90, length: 65, sleeve: 21 },
      { size: 'M', chest: 94, waist: 84, hip: 94, length: 67, sleeve: 22 },
      { size: 'L', chest: 98, waist: 88, hip: 98, length: 69, sleeve: 23 },
      { size: 'XL', chest: 102, waist: 92, hip: 102, length: 71, sleeve: 24 },
      { size: 'XXL', chest: 106, waist: 96, hip: 106, length: 73, sleeve: 25 },
    ],
    designDetails: [
      'Dark grey base with alternating wide and narrow white horizontal stripes',
      'Classic ribbed crewneck collar in matching grey',
      'Ribbed sleeve cuffs and bottom hem',
      'Relaxed comfortable slim fit',
      'Soft, breathable, and multi-scene versatile',
    ],
    description: 'Casual elegance in a stripe. This dark grey tee features alternating wide and narrow white stripes that create a sophisticated pattern. The relaxed slim fit is comfortable without sacrificing shape, making it an easy choice for everyday style that still looks put-together.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Wash dark colors separately.',
    certifications: ['OEKO-TEX Standard 100'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 'cf-tee-006',
    name: 'Black Thin-Stripe Crew Tee',
    category: 'striped-tees',
    series: 'Stripe Collection',
    images: ['/products/tee-stripe-black-detail.jpg'],
    wholesalePrice: 3.50,
    bulkPricing: [
      { minQty: 100, maxQty: 249, unitPrice: 3.50 },
      { minQty: 250, maxQty: 499, unitPrice: 3.00 },
      { minQty: 500, maxQty: null, unitPrice: 3.00 },
    ],
    moq: 100,
    leadTime: '15-18 business days',
    packaging: 'Individual polybag, 100pcs/carton',
    availableColors: [
      { name: 'Black/White', hex: '#212121' },
      { name: 'White/Black', hex: '#F5F5F5' },
    ],
    sku: 'CF-TE-006',
    material: {
      fabric: 'Soft breathable jersey knit | Lightweight and skin-friendly',
      lining: 'Skin-friendly cotton',
      craft: 'Thin horizontal stripe pattern | Embroidered logo detail',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 88, waist: 78, hip: 88, length: 64, sleeve: 20 },
      { size: 'M', chest: 92, waist: 82, hip: 92, length: 66, sleeve: 21 },
      { size: 'L', chest: 96, waist: 86, hip: 96, length: 68, sleeve: 22 },
      { size: 'XL', chest: 100, waist: 90, hip: 100, length: 70, sleeve: 23 },
      { size: 'XXL', chest: 104, waist: 94, hip: 104, length: 72, sleeve: 24 },
    ],
    designDetails: [
      'Black base with thin, evenly spaced white horizontal stripes',
      'Ribbed crewneck collar in matching black',
      'Small embroidered logo on left chest',
      'Matching embroidered detail on sleeve cuffs',
      'Also available in reverse colorway (white with black stripes)',
    ],
    description: 'A timeless striped tee with subtle branding. The black base is detailed with thin, evenly spaced white stripes for a clean, classic look. A small embroidered logo on the chest and sleeve cuffs adds a refined signature touch. Also available in a reverse white-with-black-stripes colorway.',
    careInstructions: 'Hand wash cold or machine wash gentle cycle. Lay flat to dry. Do not bleach. Low iron if needed. Durable and easy care.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: 'cf-knit-001',
    name: 'White Crewneck Long-Sleeve Sweater',
    category: 'knitwear',
    series: 'Essential Collection',
    images: ['/products/sweater-white.jpg'],
    wholesalePrice: 5.00,
    bulkPricing: [
      { minQty: 50, maxQty: 99, unitPrice: 5.00 },
      { minQty: 100, maxQty: 249, unitPrice: 4.80 },
      { minQty: 250, maxQty: null, unitPrice: 4.00 },
    ],
    moq: 50,
    leadTime: '18-25 business days',
    packaging: 'Individual polybag, 50pcs/carton',
    availableColors: [
      { name: 'White', hex: '#FFFFFF' },
    ],
    sku: 'CF-KN-001',
    material: {
      fabric: 'Lightweight fine-gauge knit | Cotton-silk blend',
      lining: 'Skin-friendly natural fiber',
      craft: 'Fine-gauge knit construction | Ribbed trim details',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sizeChart: [
      { size: 'S', chest: 92, waist: 82, hip: 92, length: 64, sleeve: 21 },
      { size: 'M', chest: 96, waist: 86, hip: 96, length: 66, sleeve: 22 },
      { size: 'L', chest: 100, waist: 90, hip: 100, length: 68, sleeve: 23 },
      { size: 'XL', chest: 104, waist: 94, hip: 104, length: 70, sleeve: 24 },
      { size: 'XXL', chest: 108, waist: 98, hip: 108, length: 72, sleeve: 25 },
    ],
    designDetails: [
      'Solid bright white in lightweight fine-gauge knit',
      'Simple crewneck collar',
      'Ribbed knit cuffs on long sleeves',
      'Ribbed knit hem at the bottom',
      'Completely plain — no patterns or logos',
    ],
    description: 'The definition of understated elegance. This lightweight crewneck sweater in pure white is crafted from a fine-gauge knit that drapes softly and breathes comfortably. Completely plain — no patterns, no logos — just pure, clean design. Perfect as a standalone piece or layered under a blazer.',
    careInstructions: 'Hand wash cold or dry clean recommended. Lay flat to dry. Do not bleach. Low iron if needed. Store folded. Wash white colors separately.',
    certifications: ['OEKO-TEX Standard 100', 'BSCI Compliant', 'ISO 9001'],
    isNew: false,
    isFeatured: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: CategorySlug): Product[] {
  if (category === 'all') return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getRelatedProducts(id: string, limit = 4): Product[] {
  const product = getProductById(id);
  if (!product) return [];
  return products
    .filter((p) => p.id !== id && p.category === product.category)
    .slice(0, limit);
}
